### ISSUE TITLE
Upload Shapefile to include  for Analysis- Shapefile does not render

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/environmental-impact#107]
Uploaded shapefile does not render in app. 
 From Draw tab:
1.Search by Placename : Eagle Lake Park, FL
2. Drag a rectangle around the area
2.Click report
3. Upload the shapefile(https://esri.box.com/s/ys8h0rdyet97ao95ujvx)
4. Note the geometry is not rendered on the map.

**Comment by CTLocalGovTeam** [comment]
@jessnoo We can display the shapefile geometry on map and also in summary report PDFs. However, could you please suggest from where we should pull the symbology to display it on map.

**Comment by jessnoo** [comment]
@CTLocalGovTeam Yes. Can we do something similar to the highlight features configuration in the config.js?  Something like this:

       // Configure graphic color to be used for uploaded shapefile used in report tab
        ReportShapfileFeaturesSymbology: {
            FillSymbolColor: "222,71,169",
            FillSymbolTransparency: "0.30",
            LineSymbolColor: "222,71,169",
            LineSymbolTransparency: "1",
            MarkerSymbolColor: "222,71,169",
            MarkerSymbolTransparency: "1"
        },

**Comment by CTLocalGovTeam** [comment]
@jessnoo Yes. We can use the above configuration structure to control the symbology for uploaded shapefiles added to analysis in report tab. We will add a separate section for this in the configuration file.

We also want to ask if we need a way to configure the symbology for uploaded shapefiles used to create AOIs in the AOI tab? As currently, only the color of polygon shapefile features can be configured using this tag below. Points and Lines are using default symbols.
```     
// Configure graphic color to be set for uploaded shapefile
        RendererColor: "28,134,238",
```

**Comment by jessnoo** [comment]
@CTLocalGovTeam Thank you. the preference on the team is to keep the config.js file as simple as possible. therefore, we would prefer:
1. To re-use the existing RendererColor parameter for the color of uploaded shapefiles.
2. That the RendererColor parameter is applied to all feature types (polygons, polylines, and points).
