### ISSUE TITLE
usability: after configuring report fields, jumps user back to the top of the panel

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#112]
in the Report tab, the user is jumped back to the top of the "Summary Report for Area of Interest" dialog after configuring report fields for a layer.  it would be nice if the dialog stayed at the same place so that the user could see the effect of turning on / off a report field without having to scroll to find the layer again.

@CTLocalGovTeam please propose a solution for this before implementing.

**Comment by CTLocalGovTeam** [comment]
@jessnoo We are analyzing this and will update you.

**Comment by CTLocalGovTeam** [comment]
@jessnoo To provide better user experience in report Tab, we tried to use scrollIntoView. Observed report panel distortion with this approach in IE browsers.  We are still looking into it.

**Comment by NikkiGolding** [comment]
@jessnoo  THis was not addressed in the drop delivered on 4/3/15

**Comment by NikkiGolding** [comment]
@jessnoo I am closing this issue. We can reopen it later if users report this as an issue.
