### ISSUE TITLE
when sharing, buffer distance not resetting to 0 as expected

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#114]
after sharing an AOI with a buffer, if the buffer distance is set to 0 and the AOI is shared again - the buffer comes back. this is true even if a new AOI is created for the second share.

steps to repro:
1. create a polygon AOI with a buffer
2. share as an email (click link and see AOI with buffer)
3. reconfigure AOI buffer to have 0 distance
4. share as an email
5. open shared link -- AOI has buffer again (with the same geometry, it seems like the share link doesn't get updated after changing the buffer...)

alternate test:
(1) create a line with a buffer, share, then create a polygon with no buffer and share -- shared polygon has buffer

alternate tests that work as expected:
(2) create a polygon with no buffer, share, then update to include a buffer and share -- the shared AOI has a buffer as expected
(3) create a line with a buffer, share, then update the buffer distance to something not 0 and share again -- shared AOI is defined as expected

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have resolved this in version 1.1. However it was not mentioned in the pull request.

**Comment by jessnoo** [comment]
@CTLocalGovTeam Yes, i see now that is was resolved. Thank you.
