### ISSUE TITLE
Bearings and Distance: Enter on keyboard is same as clicking Add

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#124]
when entering bearings and distances, after valid values are entered for both parameters, hitting enter on the keyboard should do the same thing as clicking Add AND control is now in the new row bearing box to continue entering values efficiently. 

this would allow a user with a string of bearings and distances to do all entry with the keyboard instead of having to switch between the keyboard and the mouse for each record

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have incorporated this and will deliver it in next release.
