### ISSUE TITLE
Time zone should be indicated in the reports

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#134]
Based on Kathleen's team's feedback.  The timezone should be indicated in the reports.

**Comment by CTLocalGovTeam** [comment]
@lindsayking, @jessnoo  We can implement this change. Please suggest one of the formats from below.

![image](https://cloud.githubusercontent.com/assets/2959186/6826835/0b82b380-d32a-11e4-96cf-a716709d0c64.png)

**Comment by jessnoo** [comment]
@CTLocalGovTeam Please use Style D1

![image](https://cloud.githubusercontent.com/assets/6181441/6848233/41f5e48c-d389-11e4-8935-9d3a9d1c16af.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking @jessnoo Currently, the time reported in the PDF is the server time on which the GP service executes. We think that adding timezone information will surely help users to understand and relate to the report creation time. 

We are thinking that we can provide a better implementation by printing the client's local time(including timezone info). So users can easily understand the report creation time. To achieve this we will have to introduce an additional GP service parameter which will accept the report creation time sent by the application. 

Please let us know your thoughts on this.

**Comment by jessnoo** [comment]
@CTLocalGovTeam 

We agree that the ideal is to have the client's time represented in the report but, at this time, we would prefer not to make changes to the GP tools. 

Please simply add the time zone information to the current time stamp for the April release.
