### ISSUE TITLE
When app is localized, AOI graphic is not persisted in shared version of the app

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#142]
Steps to repro:
1)  Every string in the localizedStrings.js for http://54.241.236.56/EnvImpact0.14server/ has been modified.  Using http://54.241.236.56/EnvImpact0.14server/, launch the app and click OK in the splash screen.
2) Use any method to define an AOI (e.g. rectangle draw)
3) Share the app using any method
4) Open the shared version of the app.  Notice that the extent is shared correctly, but the AOI graphic is not present in the shared version.

For example, http://bit.ly/1xZuOEQ was generated from http://54.241.236.56/EnvImpact0.14server/ with an AOI created from a placename search.  The expanded shared URL includes "TAB:APlacename$ADDR:null$".  We've discovered that if the "A" in "TAB:APlacename$ADDR:null$" is removed, the AOI graphic shares successfully.

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have fixed this issue and will include the fix in next release.

**Comment by jessnoo** [comment]
Verified in V1.2
