### ISSUE TITLE
Improve UX while waiting for excel, fgdb, and shapefile exports

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#160]
When the user chooses to export information in excel, file geodatabase, or shapefile - they also must choose to download a report.

The loading spinner comes up and indicates that the application is working on the request. 

this spinner goes away when any one of the things finishes. In the case the report is the first thing to finish - there is no additional indication that the additional request for an export is still processing. 

Is there a way to indicate to the user that the app is still working on something?

**Comment by CTLocalGovTeam** [comment]
@jessnoo Instead of stopping the loading indicator after finishing the downloading of first report, the app will keep on displaying loading indicator till all types of reports are downloaded. Please confirm.

**Comment by jessnoo** [comment]
@CTLocalGovTeam Yes, please proceed.

**Comment by NikkiGolding** [comment]
@jessnoo  THis is partially fixed. Want to get your take on it. Let's discuss.
