### ISSUE TITLE
For Coordinate input, if placename search used to define starting point, AOI not reflected in shared version

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#163]
Steps to repro:
1) Launch the app and click ok on the splash screen
2) on the AOI tab, select the Coordinates option for AOI input
3) use the address search option to define the starting point
4) Add bearings and distances off of the address starting point, then provide a buffer distance
5) Share the app
6) Open the shared version of the app.  Note the AOI is not visible in the shared version of the app

**Comment by CTLocalGovTeam** [comment]
We have fixed this issue and will include the fix in next release

**Comment by NikkiGolding** [comment]
@jessnoo please validate.

**Comment by jessnoo** [comment]
Verified in v1.2
