### ISSUE TITLE
Quick summary and in-app report measurements incorrect

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#164]
Using Florida Managed Areas as an example:

Looking [at the webmap](http://www.arcgis.com/home/webmap/viewer.html?webmap=f4d5400279f747f6a571194dd592dd55), the table for the Florida Managed Areas shows the Shape_Area field, which is in meters:

![image](https://cloud.githubusercontent.com/assets/4316336/6180248/068ef88e-b2d7-11e4-99d0-2f478ad3be5e.png)

However, on the report tab and in the quick summary report, these same area numbers are reported, despite being in acres rather than meters.

![image](https://cloud.githubusercontent.com/assets/4316336/6180325/26dbf528-b2d8-11e4-9a08-687904eaf06e.png)

It appears as if the units are not being read from the service correctly, which in turn is causing measurements to be incorrect in the in-app and quick summary reports.  

The Bull Creek Scrub Florida Managed Area is 3.146 square kilometers in area, but the in-app report and quick summary report show it as 12,735.413 square kilometers/3,146,989.139 acres.

@jessnoo

**Comment by jessnoo** [comment]
@CTLocalGovTeam We are seeing this issue again in V1.2. Can you please assess our configuration?

http://50.18.115.76/EnvImpact1.2UAT/wm/

Please do not take any action until conferring with the Esri team.

**Comment by jessnoo** [comment]
Verified in v1.3
