### ISSUE TITLE
Sharing to Facebook results in + in search strings

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#171]
When sharing the application through Facebook, the search strings that get populated have plus signs (+) in them ... 

![image](https://cloud.githubusercontent.com/assets/6181441/6332989/562cfab6-bb3e-11e4-8de1-14afed2e913e.png)

**Comment by CTLocalGovTeam** [comment]
@jessnoo We are unable to reproduce this issue on http://50.18.115.76/EnvImpactUAT/server/.

Following are the steps we tried to reproduce this issue are:
1. Search for an address from Placename/Draw/Coordinates
2. Click on share icon
3. Select facebook to share
4. Click on share link button on facebook share page
5. Click on the shared link from facebook wall

Please let us know if we are missing any steps

**Comment by jessnoo** [comment]
@CTLocalGovTeam Yes! I was clicking on the link from the sharing dialog, not the link from the post on the wall.
