### ISSUE TITLE
Application title disappears and should continue doing ...

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#172]
In portrait mode on a table, the application title disappears completely. it should remain with the ...
shorten the visible area for the title of the application.

Short title example ... 
![image](https://cloud.githubusercontent.com/assets/6181441/6333826/17c27380-bb45-11e4-923d-654477532b32.png)

Short title disappears unnecessarily ... 
![image](https://cloud.githubusercontent.com/assets/6181441/6333956/2a857fb6-bb46-11e4-9ebc-961e0483cf95.png)

Long title example with "..." ... the ellipsis shows up --
![image](https://cloud.githubusercontent.com/assets/6181441/6333937/081536e2-bb46-11e4-8c3b-b6adf356b034.png)

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have fixed this issue and will include this in next release.
