### ISSUE TITLE
Pop Up title should be given more room

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#173]
it seems like more text could be shown in the pop up title. 

in this example, why can't the whole word "mangrove" show up before the ellipsis starts?

![image](https://cloud.githubusercontent.com/assets/6181441/6334012/950d3432-bb46-11e4-879a-7feb465fc045.png)

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have implemented the approach mentioned in the Esri/site-selector#119. We will include this in the next release.
