### ISSUE TITLE
Basemap credits don't reflect current basemap

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#177]
the basemap credits shown at the bottom of the map do not update as the basemap switches. 

![image](https://cloud.githubusercontent.com/assets/6181441/6355851/f3e75b82-bc0d-11e4-8089-d861d8b69ab0.png)

**Comment by lindsayking** [comment]
FYI - related to https://github.com/Esri/site-selector/issues/135

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam  The basemap credits do not update when the basemap changes. The credits do update after the basemap is switched and the user refreshes the map.
