### ISSUE TITLE
Point symbols are compressed vertically in the legend

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#178]
Point symbols are compressed vertically in the legend

![image](https://cloud.githubusercontent.com/assets/6181441/6355967/ea9f2b94-bc0e-11e4-9e9e-28ef19a13d1d.png)

**Comment by CTLocalGovTeam** [comment]
@lindsayking @jessnoo Below is the screenshot for map legend with 36 pixel height.

![legend with 36 px](https://cloud.githubusercontent.com/assets/2959186/6639927/d9848c74-c9b9-11e4-91be-b6d4a8b730bb.PNG)

The image sizes for Left and Right scroll buttons will be increased to match the height of the legend bar. This will be a deviation from standard image sizes. 
Please confirm if we should proceed with this.

**Comment by CTLocalGovTeam** [comment]
@Lindsay K @Jesnoo
We are awaiting your confirmation on the approach outlined in the previous comment.

**Comment by jessnoo** [comment]
@CTLocalGovTeam Yes, the approach to expand the height of the legend bar is ok.  Please make sure take this same approach with https://github.com/Esri/live-work-locate/issues/120

**Comment by CTLocalGovTeam** [comment]
@jessnoo Ok. We will increase the height of legend bar and Left and Right scroll buttons. We will also follow the same approach in Esri/live-work-locate#120 .
We will provide this in the next release.
