### ISSUE TITLE
Geosearch brings back records that sometimes don't make sense

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#181]
when searching for 'Miami' for examples, there are many city POIs returned - these responses include the City name and state/country in the name. when they appear in the app, it's easy to understand what these are. there are also many responses that just say 'Miami' -- it's not easy for the user to understand what this location is... 

![image](https://cloud.githubusercontent.com/assets/6181441/6360276/b407149c-bc2d-11e4-9414-bc61efc26d2e.png)

these candidates don't have enough information to be useful for the user. 

options to resolve:
- add a category filter to the request to only bring back a select type of POI. Reference for categories: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-category-filtering.htm
- include the type characteristic in the list for the user
- also bring back "Place_Addr" with the initial request and include that in the list for the user

a few example candidates being returned from the Miami search:
![image](https://cloud.githubusercontent.com/assets/6181441/6360394/8120dc24-bc2e-11e4-897a-4575af41fb04.png)

@HeatherEisan

**Comment by CTLocalGovTeam** [comment]
@jessnoo 
Including the type characteristic may not work as there could be two or more "Miami, Shopping Center" that are located at different places. 

Using place_addr in the address list may not work as this field does not return a value with every candidate result. It is often empty ```""``` 

We feel that option 1 makes most sense i.e., using category filters. This way users will have more control over what gets displayed in search results. Please see screenshot for an e.g., 
![image](https://cloud.githubusercontent.com/assets/2959186/6729618/14079856-ce5a-11e4-80a1-5c2aa94594f5.png)

**Comment by jessnoo** [comment]
@CTLocalGovTeam Agreed, however please do not expose the placenamesearch filtering options in the configuration file. the filters that you have identified above will work for this release.

**Comment by CTLocalGovTeam** [comment]
@jessnoo just to confirm, are you suggesting we should hard code these filter options (for POIs) and not expose them in the configuration file?

**Comment by jessnoo** [comment]
@CTLocalGovTeam Initially yes, however, we have reevaluated. Please move forward with exposing the PlaceNameSearch configuration options in the config.js as you have proposed.
