### ISSUE TITLE
Unified query returns no results when there are some

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#189]
observe the behavior here: http://50.18.115.76/EnvImpactUAT/server with these examples searching for records in the Eagle Nesting Locations layer:

NestID = PO184 
Fails: PO184
Pass: PO
Pass 184

NestID = HL022
Fails: HL022
Pass: HL
Fails: 022

Looking at the request being sent from the app, it appears valid responses are coming back even though the app reports nothing.   sample query that the app sends is below for the PO184 search (with format switched from json to html for easier human interaction.

http://50.18.115.76:6080/arcgis/rest/services/EIA_V101UAT/EIAAnalysis/MapServer/0/query?f=html&where=UPPER(NestID)%20LIKE%20UPPER(%27%25PO184%25%27)%20AND%201425337173918%3D1425337173918&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have implemented this change and will include this in next release
