### ISSUE TITLE
Reduce and minimize use of global variables in dojo global variable

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#191]
Related to https://github.com/Esri/configurable-locator/issues/126.  

Code needs to be reviewed and modified to reduce, minimize and limit the number of global variables into the dojo global variable. This work will have the benefit of easier code maintenance over time.  This should be done throughout the codebase.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We are implementing this as per the approach detailed in Esri/site-selector#133 .

Please confirm

**Comment by lindsayking** [comment]
@CTLocalGovTeam - please see response by @LindsayThomas at https://github.com/Esri/site-selector/issues/133.

**Comment by NikkiGolding** [comment]
@MikeTschudi  Please verify

**Comment by MikeTschudi** [comment]
The project has been converted successfully from using "dojo" to using "appGlobals" for its global variables.
