### ISSUE TITLE
Formatting changes in Report Panel

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#193]
Please make the following format changes in the Report panel:

1. Capitalize the word presenting what is being measured:
   - area should be Area
   - length should be Length
   - count should be Count

2. Lower case the units of measure:
   - Miles should be miles
   - Acres should be acres
   - Kilometer should be km
   - Sq.Km. is preferred to be km^2 -- is it possible to have text be superscript that it looks like this: 
     ![image](https://cloud.githubusercontent.com/assets/6181441/6493859/8ed61e48-c272-11e4-806a-34004248a773.png)

3. There is an unnecessary space on the point counts. only add a space when a summary value requires a units of measure.
   ![image](https://cloud.githubusercontent.com/assets/6181441/6493879/bd12fe84-c272-11e4-87a8-30f1fdc0d61a.png)

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have implemented the changes and will include in next release
