### ISSUE TITLE
Improve error message when selected AOI geometry is too complex and the buffer calculation fails

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#194]
The user may select features in the map that are too complicated to send through the simplify task on the geometry service, but the error message is not friendly:  

![image](https://cloud.githubusercontent.com/assets/6181441/6493958/4d8fced8-c273-11e4-8e81-4e401ec5ebb5.png)

Please update the error message to "Unable to buffer feature."

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have implemented this change and will include this in next release
