### ISSUE TITLE
Pop-ups: Long strings run out of the window

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#195]
When a value displayed in the pop up is a long, continuous string, the string gets cut off by the size of the pop up window:
![image](https://cloud.githubusercontent.com/assets/6181441/6495039/43bee670-c27b-11e4-8300-de43e05542df.png)

if there are spaces, then the string continues on the next line. 

Please propose a solution to the long, continuous string problem before implementing.

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have fixed this issue and will include in next release

**Comment by jessnoo** [comment]
@CTLocalGovTeam How have you planned to address this issue?

**Comment by CTLocalGovTeam** [comment]
@jessnoo  Key and value each occupy 50% of the width. They are wrapped individually when longer text is set.

**Comment by jessnoo** [comment]
@CTLocalGovTeam Ok. how will the string in the above example be handled with this approach?

**Comment by CTLocalGovTeam** [comment]
@jessnoo The strings in the above example will be wrapped as indicated in the below snapshot.

![image](https://cloud.githubusercontent.com/assets/2959186/6708921/b990fc1a-cd9a-11e4-9034-4e7821b8dcd5.png)

**Comment by jessnoo** [comment]
@CTLocalGovTeam thank you. in the case that the string is longer than the space available, such as the original example, what will happen?

https://cloud.githubusercontent.com/assets/6181441/6495039/43bee670-c27b-11e4-8300-de43e05542df.png

**Comment by NikkiGolding** [comment]
@jessnoo  Please validate

**Comment by jessnoo** [comment]
Validated in V1.2
