### ISSUE TITLE
Show details in report panel when uploaded analysis shapefile returns no results

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#196]
When a shapefile uploaded for analysis does not intersect the AOI, the user is shown a message "No features found in AOI" and then nothing else happens. 

Please treat the shapefile the same as other analyzed layers and show the shapefile name in the report panel with "No results found" .

**Comment by CTLocalGovTeam** [comment]
@jessnoo We have implemented this change and will include this in next release
