### ISSUE TITLE
Analyzer reporting error when publishing GenerateImpactReport 

### ISSUE THREAD

**Issue by lindsayking** [Esri/environmental-impact#204]
@CTLocalGovTeam 
The analyzer is reporting an error "Script GenerateImpactReport contains broken project data source: A4 Portrait."  This error prevents the user from being able to publish the tool.

We are seeing this behavior on ArcGIS 10.1 and 10.2.  It does not appear to be an issue with 10.2.2, 10.3 or 10.3.1.  

Steps to repro:
1) In ArcGIS 10.1sp1QIP or ArcGIS 10.2, run the GenerateImpactReport tool.
2) From the result, select to publish as a geoprocessing service.
3) After making the [necessary changes](http://solutions.arcgis.com/state-government/help/environmental-impact/get-started/publish-service/) in the Service Editor window, click Analyze. 
4) Note the analyzer reports the error message and you are unable to successfully publish the tool.

**Comment by jessnoo** [comment]
@CTLocalGovTeam provided fix instructions on May 4, 2015. Fix was implemented, tested, and merged.
