### ISSUE TITLE
Display 'N/A' instead of zeroes in detailed summary report when there is no potential impact

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/environmental-impact#207]
Display “N/A” in place of zeroes, only in the Summary of Potential Impact table at the top of the detailed summary report. 
* For point layers, zero is displayed for Counts if no results are found within AOI, “N/A” for Area and Length columns
* For line layers, zero is displayed for Length if no results are found within AOI, “N/A” is displayed for Count and Area columns
* For polygon layers, zero is displayed for Area if no results are found within AOI, “N/A” is displayed for Count and Length columns

**Comment by jessnoo** [comment]
Verified. Included in August 2015 Solutions Release.
