### ISSUE TITLE
Disable Geolocation by commenting it out in the config.js 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/environmental-impact#220]
also, add this comment

The geolocation button has been hidden from the user interface by commenting out the widgetpath for geolocation below. You can enable geolocation by uncommenting the widgetpath for geolocation. The geolocation button, however, will only work on browsers supporting geolocation over HTTP connections.  If a browser requires a HTTPS connection to support geolocation and the button is enabled, the button will not work, but the application will work correctly otherwise.

**Comment by LindsayThomas** [comment]
committed.

FYI @jessnoo @lindsayking 
Need to test this before packaging

**Comment by lindsayking** [comment]
This has been tested.
