### ISSUE TITLE
Revision in the position of tabs after including "Report" tab in ConfigUI

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/environmental-impact#224]
Below are the images of ConfigUI after incorporating "Report" tab:
### General Tab: 
![image](https://cloud.githubusercontent.com/assets/2959186/21349406/c8f8d00a-c6d7-11e6-880d-0841832d8179.png)
### Analysis Tab: 
![image](https://cloud.githubusercontent.com/assets/2959186/21349310/446541a2-c6d7-11e6-9999-692455aca9c3.png) 
### Download Tab: 
![image](https://cloud.githubusercontent.com/assets/2959186/21349341/66f3793c-c6d7-11e6-86ce-d143753f1d22.png)
### Report Tab: 
![image](https://cloud.githubusercontent.com/assets/2959186/21349352/76f06c8c-c6d7-11e6-88fb-5b498b497930.png) 
### Search Source Setting Tab: 
![image](https://cloud.githubusercontent.com/assets/2959186/21349363/8875c29a-c6d7-11e6-98f2-9c477b29a4a2.png)

**Comment by jessnoo** [comment]
submitted to incorrect repo. already addressed screening-widget repo
