### ISSUE TITLE
ENH-000105033  Add a configuration option to the Environmental Screening Web AppBuilder widget to remove the buffer parameter when drawing points and lines.

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/environmental-impact#226]
<div><div>
<span><b>Salesforce ID:</b> ENH-000105033</span><br/>
<span><b>Salesforce Submitter:</b> Bradley Snider</span><br/>
<span><b>Salesforce Submit Date:</b> 5/09/2017 4:49 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Low</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.  <br>Remove the buffer parameter when drawing points and lines.<br>2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br>The customer would like streamline the widget for end users by removing the &#39;Buffer distance&#39; settings in the widget interface.  While they can set the default to 1 foot, this clutters the interface.<br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br>It improves their end user experience.</span><br/>
<span><b>Product:</b> ArcGIS for State Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for State Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> N/A</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Issue will be addressed in 5.2.</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
We will not make this enhancement.
